spring.application.name=controlF

spring.datasource.url=jdbc:postgresql://localhost:5432/controlf
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
