spring.application.name=controlF

spring.datasource.url=jdbc:postgresql://localhost:5432/controlf
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
